name: mood_tracker
description: Simple bilingual Mood Tracker app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
flutter_animate: ^2.0.0  # Để thêm animations dễ dàng
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/avatar.png
